package ru.pkstudio.localhomeworkandtaskmanager.ui.theme

import androidx.compose.ui.graphics.Color


val lightGray = Color(0xFFBCBCBC)

val success = Color(0xFF08A70E)

val filledColor = Color(0xFF636363)
val emptyColor = Color(0xFFC4C4C4)
val background = Color(0xFF1F1200)

val kanbanHeaderText = Color(0xFFEDEDED)
val onDarkCardText = Color(0xFFD6D6D6)
val onLightCardText = Color(0xFF1D1D1D)

val primaryLightMediumContrast = Color(0xFF2C3167)
val onPrimaryLightMediumContrast = Color(0xFFFFFFFF)
val primaryContainerLightMediumContrast = Color(0xFF6468A2)
val onPrimaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val secondaryLightMediumContrast = Color(0xFF333548)
val onSecondaryLightMediumContrast = Color(0xFFFFFFFF)
val secondaryContainerLightMediumContrast = Color(0xFF6B6B81)
val onSecondaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryLightMediumContrast = Color(0xFF6A6969)
val onTertiaryLightMediumContrast = Color(0xFF295FC0)
val tertiaryContainerLightMediumContrast = Color(0xFF88617A)
val onTertiaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val errorLightMediumContrast = Color(0xFF740006)
val onErrorLightMediumContrast = Color(0xFFFFFFFF)
val errorContainerLightMediumContrast = Color(0xFFCF2C27)
val onErrorContainerLightMediumContrast = Color(0xFFFFFFFF)
val backgroundLightMediumContrast = Color(0xFFFBF8FF)
val onBackgroundLightMediumContrast = Color(0xFF1B1B21)
val surfaceLightMediumContrast = Color(0xFFFBF8FF)
val onSurfaceLightMediumContrast = Color(0xFF111116)
val surfaceVariantLightMediumContrast = Color(0xFFE3E1EC)
val onSurfaceVariantLightMediumContrast = Color(0xFF35353E)
val outlineLightMediumContrast = Color(0xFF52525B)
val outlineVariantLightMediumContrast = Color(0xFF6D6C76)
val scrimLightMediumContrast = Color(0xFF000000)
val inverseSurfaceLightMediumContrast = Color(0xFF303036)
val inverseOnSurfaceLightMediumContrast = Color(0xFFF2EFF7)
val inversePrimaryLightMediumContrast = Color(0xFFBEC2FF)
val surfaceDimLightMediumContrast = Color(0xFFC8C5CD)
val surfaceBrightLightMediumContrast = Color(0xFFFBF8FF)
val surfaceContainerLowestLightMediumContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightMediumContrast = Color(0xFFF5F2FA)
val surfaceContainerLightMediumContrast = Color(0xFFEAE7EF)
val surfaceContainerHighLightMediumContrast = Color(0xFFDEDCE3)
val surfaceContainerHighestLightMediumContrast = Color(0xFFD3D0D8)

val primaryDarkMediumContrast = Color(0xFFD8D9FF)
val onPrimaryDarkMediumContrast = Color(0xFF1B2055)
val primaryContainerDarkMediumContrast = Color(0xFF878CC8)
val onPrimaryContainerDarkMediumContrast = Color(0xFF000000)
val secondaryDarkMediumContrast = Color(0xFFDBDAF3)
val onSecondaryDarkMediumContrast = Color(0xFF232436)
val secondaryContainerDarkMediumContrast = Color(0xFF8F8FA6)
val onSecondaryContainerDarkMediumContrast = Color(0xFF000000)
val tertiaryDarkMediumContrast = Color(0xFF666666)
val onTertiaryDarkMediumContrast = Color(0xFFDFDFDF)
val tertiaryContainerDarkMediumContrast = Color(0xFFAE849E)
val onTertiaryContainerDarkMediumContrast = Color(0xFF000000)
val errorDarkMediumContrast = Color(0xFFFFD2CC)
val onErrorDarkMediumContrast = Color(0xFF540003)
val errorContainerDarkMediumContrast = Color(0xFFFF5449)
val onErrorContainerDarkMediumContrast = Color(0xFF000000)
val backgroundDarkMediumContrast = Color(0xFF131318)
val onBackgroundDarkMediumContrast = Color(0xFFE4E1E9)
val surfaceDarkMediumContrast = Color(0xFF131318)
val onSurfaceDarkMediumContrast = Color(0xFFFFFFFF)
val surfaceVariantDarkMediumContrast = Color(0xFF46464F)
val onSurfaceVariantDarkMediumContrast = Color(0xFFDDDBE6)
val outlineDarkMediumContrast = Color(0xFFB2B1BB)
val outlineVariantDarkMediumContrast = Color(0xFF908F99)
val scrimDarkMediumContrast = Color(0xFF000000)
val inverseSurfaceDarkMediumContrast = Color(0xFFE4E1E9)
val inverseOnSurfaceDarkMediumContrast = Color(0xFF2A292F)
val inversePrimaryDarkMediumContrast = Color(0xFF3E437A)
val surfaceDimDarkMediumContrast = Color(0xFF131318)
val surfaceBrightDarkMediumContrast = Color(0xFF44444A)
val surfaceContainerLowestDarkMediumContrast = Color(0xFF07070C)
val surfaceContainerLowDarkMediumContrast = Color(0xFF1D1D23)
val surfaceContainerDarkMediumContrast = Color(0xFF27272D)
val surfaceContainerHighDarkMediumContrast = Color(0xFF323238)
val surfaceContainerHighestDarkMediumContrast = Color(0xFF3D3D43)

val importance1 = Color(0xFFE6E6FA)
val importance2 = Color(0xFFD8E4E6)
val importance3 = Color(0xFFE0E4CC)
val importance4 = Color(0xFFF5D5D0)
val importance5 = Color(0xFFF0C4B4)
val importance6 = Color(0xFFF4A261)
val importance7 = Color(0xFFE76F51)
val importance8 = Color(0xFFF72585)
val importance9 = Color(0xFFD00000)
val importance10 = Color(0xFF9D0208)

val stageVariant1 = Color(0xFFA34747)
val stageVariant2 = Color(0xFFA36847)
val stageVariant3 = Color(0xFFA38A47)
val stageVariant4 = Color(0xFF8DA347)
val stageVariant5 = Color(0xFF5EA347)
val stageVariant6 = Color(0xFF47A36B)
val stageVariant7 = Color(0xFF47A38D)
val stageVariant8 = Color(0xFF479EA3)
val stageVariant9 = Color(0xFF477CA3)
val stageVariant10 = Color(0xFF475AA3)
val stageVariant11= Color(0xFF6147A3)
val stageVariant12 = Color(0xFF8347A3)
val stageVariant13 = Color(0xFFA3479F)
val stageVariant14 = Color(0xFFA3477E)
val stageVariant15 = Color(0xFFA3475C)
val stageVariant16 = Color(0xFFA34747)
val stageVariant17 = Color(0xFF8D6B47)
val stageVariant18 = Color(0xFF6B8D47)
val stageVariant19 = Color(0xFF476B8D)
val stageVariant20 = Color(0xFF6B478D)
